colorScheme          = "congo"
defaultAppearance    = "auto"
autoSwitchAppearance = true
enableDarkModeToggle = true
enableSearch         = true
enableCodeCopy       = true
mainSections         = ["post", "talk"]
images               = ["img/logo_background.png"]

[social]
  twitter = "ender2025"

[homepage]
  layout       = "custom"
  showRecent   = true
  recentLimit  = 10

[article]
  showReadingTime = false
