# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            James Pogran
tagline:          Ender
url:              http://jamespogran.com
paginate:         1
baseurl:          /
author:
  name:           James Pogran
  url:            https://twitter.com/ender2025
  email:          james.pogran@outlook.com

# Custom vars
version:          1.0.0
# github:
#   repo:           https://github.com/poole/poole
