title: James Pogran
email: james.pogran@outlook.com
description: "Adventures in Devops on Windows"
url: "http://jamespogran.com"
baseurl: ""
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

twitter_username: ender2025
github_username:  jpogran
stackoverflow_username: users/1083/james-pogran

google_analytics_ua: UA-74930020-1

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

gems: [jekyll-paginate]  
# https://www.packtpub.com/books/info/authors/james-pogran
