title: James Pogran
email: james.pogran@outlook.com
description: "Adventures in Devops on Windows"
url: "http://jamespogran.com"
baseurl: ""
permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
excerpt_separator: <!--more-->

twitter_username: ender2025
github_username:  jpogran
stackoverflow_username: "1083/james-pogran"
stackoverflow_username_short: "james-pogran"

google_analytics_ua: UA-74930020-1

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  
# https://www.packtpub.com/books/info/authors/james-pogran
