# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            James Pogran
tagline:          'James Pogran'
description:      'A site'
url:              http://jamespogran.com
baseurl:          /

author:
  name:           'James Pogran'
  url:            https://twitter.com/ender2025

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jpogran
