baseURL      = "https://jpogran.github.io"
title        = "James Pogran"
author       = "James Pogran"
copyright    = "Copyright © 2008–2020, James Pogran; all rights reserved"
languageCode = "en-us"

[permalinks]
  books = "/:title/"
  posts = "/:title/"
  talks = "/:title/"

[taxonomies]
  series = "series"
  tags = "tags"

[params]
  author           = "James Pogran"
  introDescription = "The intersection of Prose and Technology"
  images           = ["img/learning_powershell_dsc_second_edition.png"]
  twitter          = "@ender2025"
  ga_analytics     = "UA-74930020-1"
  numberOfTagsShown = 14
  # will be used on share >> twitter, facebook, linkedin
  fallBackOgImage = "img/learning_powershell_dsc_second_edition.png"
  # sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
  codeMaxLines = 10
  # disable showing line numbers by default. Switch to `true` if you'd rather have them on.
  codeLineNumbers = true
  # directory(s) where your articles are located
  mainSections = ["post", "talk"] # see config details here https://gohugo.io/functions/where/#mainsections
  # center logo on navbar
  centerLogo = false # Set to "true" for centering or "false" for left aligned.
  # logo = "icons/favicon-32x32.png"
  # Label Non inline images on an article body
  figurePositionShow = false # toggle on or off globally
  # you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
  figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0
  # Set the collapsed mobile navigation to either appear from the left or the right
  mobileNavigation = "left" # if you prefer right change to 'right'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
